# git-cliff configuration for changelog generation
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
  ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
  ## [Unreleased]
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
  ### {{ group | striptags | trim | upper_first }}
  {% for commit in commits %}
    - {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
  {%- endfor %}
{% endfor %}\n
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 3 -->🔨 Refactor" },
  { message = "^style", group = "<!-- 4 -->🎨 Styling" },
  { message = "^doc", group = "<!-- 5 -->📝 Documentation" },
  { message = "^test", group = "<!-- 6 -->🧪 Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps\\)", group = "<!-- 7 -->📦 Dependencies" },
  { message = "^chore|^ci", group = "<!-- 8 -->⚙️ Miscellaneous" },
  { body = ".*security", group = "<!-- 9 -->🔒 Security" },
]
filter_commits = false
tag_pattern = "v[0-9].*"
sort_commits = "newest"
